### ISSUE TITLE
How do I download this to minecraft?

### ISSUE THREAD

**Issue by Miboi** [Coderx-Gamer/ui-utils#10]
Hello, how do I download this to minecraft and make it work? I dont know what file I have to download.

**Comment by SzczurekYT** [comment]
> Hello, how do I download this to minecraft and make it work? I dont know what file I have to download.

Download the mod jar form releases page and put it in your mods folder like any other mod.
It's fabric mod.
If you don't know how to install fabric mods, look online, there are many tutorials.

**Comment by Anonymous17532** [comment]
download fabric api and fabric thingy and put this in .minecraft/mods
if mods folder is not there name it "mods"
