### ISSUE TITLE
wont dupe

### ISSUE THREAD

**Issue by batman19733** [Coderx-Gamer/ui-utils#104]
can the mod dupe stuff?cuz for me it wont dupe was it fix or it isent meant to dupe?

**Comment by batman19733** [comment]
i am dumb
XD

**Comment by jaaloley** [comment]
how

**Comment by batman19733** [comment]
what how?

its doesnt need to dupe?

**Comment by maxwell-com** [comment]
No, its a dupe hunter. By messing around the with the packets, the server and client make become out of sync leading you to two copies of something or making the server update your inventory twice, or something like that.

**Comment by MrBreakNFix** [comment]
correct
