### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Najtmerko** [Coderx-Gamer/ui-utils#11]
hello anyone who can tell me what do I do ? 
![DIFU](https://user-images.githubusercontent.com/113385312/189740455-b9a58f5a-de3d-4cf5-a55d-b1970c851923.png)

**Comment by GDMgmer3992** [comment]
Try Set Your environment to the location they suggested

**Comment by Anonymous17532** [comment]
Try building it in intellij first, it sometimes is missing libraries and will fix it
Also try downloading a direct JAR and putting it in your mods folder along with fabric API 
https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Anonymous17532** [comment]
Also you do need java to build it lol

**Comment by Anonymous17532** [comment]
if you need more help make a new issue

also look it up on youtube or something 
"how to install hava"
