### ISSUE TITLE
Any chance of making it compatible for 1.16.5?

### ISSUE THREAD

**Issue by Phthermal** [Coderx-Gamer/ui-utils#110]
My pc only supports upto 1.16.5. Can you please make it compatible for 1.16.5.

**Comment by MrBreakNFix** [comment]
bro why does your pc only suppoort 1.16.5 thats just whack man

**Comment by Phthermal** [comment]
> bro why does your pc only suppoort 1.16.5 thats just whack man

My parents would just kick me out of the house if I try to ask for a new processor. Please make one for 1.16.5.

**Comment by Phthermal** [comment]
> bro why does your pc only suppoort 1.16.5 thats just whack man

Or is there any way to downgrade it?

**Comment by MrBreakNFix** [comment]
its possible but you dont need a new processor to update minecraft...

**Comment by Phthermal** [comment]
> its possible but you dont need a new processor to update minecraft...

I have a cheap processor intel i3 2120. i can't go any further than 1.16.5. My system meets all the remaining requirements except that.

**Comment by MrBreakNFix** [comment]
:o) what happens if you try it? send me a screenie

**Comment by Phthermal** [comment]
![Uploading Screenshot_20230824-165745.png…]()

**Comment by Phthermal** [comment]
It shows:- glfw error 65542.
Maybe my drivers doesn't support opengl 4.2

**Comment by Phthermal** [comment]
[
![image](https://github.com/Coderx-Gamer/ui-utils/assets/142642287/15332715-63f5-4660-9f77-646779450294)
](url)

**Comment by MrBreakNFix** [comment]
hmm ill look into it

**Comment by MrBreakNFix** [comment]
I dont really see the reason of using this mod anyway on 1.16.5, unless you have some servers on it

**Comment by Phthermal** [comment]
Can you please make it quick I have a server to dupe 🥺

**Comment by Ragua7065** [comment]
Sir I also have the same issue , I am also waiting for your response = )

**Comment by Phthermal** [comment]
> Sir I also have been facing the same issue , I am also waiting for your response = )

Just get a 3rd gen processor or a graphics card

**Comment by Ragua7065** [comment]
> > Sir I also have been facing the same issue , I am also waiting for your response = )
> 
> Just get a 3rd gen processor or a graphics card
I know but its a laptop so I cant upgrade And also I m a kid so cant buy

**Comment by Ragua7065** [comment]
I know the issue is with the graphic card but firstly its a laptop and secondly I m a kid so I cant buy . (my laptop is 12 year old with 1st gen processor)

**Comment by Coderx-Gamer** [comment]
Maybe you guys should get cpus made after the great depression and then see if they can run 1.20.
