### ISSUE TITLE
1.3.2 Requires any version of fabric

### ISSUE THREAD

**Issue by deathrow123456778899** [Coderx-Gamer/ui-utils#111]
I installed fabric 1.20.1 into my mods folder, but when minecraft loads up the language are squares only and once I join a minecraft server, the game crashes. 
![Capture](https://github.com/Coderx-Gamer/ui-utils/assets/145817832/969cc5b7-8041-4605-aaae-f0fb887bcf66)
![Capture](https://github.com/Coderx-Gamer/ui-utils/assets/145817832/1949ab2b-f5af-4e82-a0c0-846e18600d95)

These are both photos on what is going on. During the crash I have fabric api 1.20.1 installed to the mods folder.

**Comment by Eragon1250** [comment]
i have the same problem, but for me minecraft dosent loads up, i get the error immediatly

Error Code Copyd;

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'UI Utils' (uiutils) 1.3.2 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MrBreakNFix** [comment]
Did bot of you have fabric and fabric api installed?

**Comment by Coderx-Gamer** [comment]
You probably forgot to add fabric api. I'm closing this cause its inactive.
