### ISSUE TITLE
Fabricating Packet button crash

### ISSUE THREAD

**Issue by JustLikeNone** [Coderx-Gamer/ui-utils#114]
When pressing Fabrication packets it crashes

here is the log 
https://mclo.gs/CCUfvR8

**Comment by MrBreakNFix** [comment]
Are you on mac?

**Comment by JustLikeNone** [comment]
> Are you on mac?

no
Windows

**Comment by MrBreakNFix** [comment]
Have you tried removing some of those other mods?

**Comment by JustLikeNone** [comment]
> Have you tried removing some of those other mods?

no

**Comment by MrBreakNFix** [comment]
Try it in its own instance and see if that fixes it.

**Comment by JustLikeNone** [comment]
> Try it in its own instance and see if that fixes it.

it works si there is a mod incompatiable

**Comment by MrBreakNFix** [comment]
Looks good!

**Comment by JustLikeNone** [comment]
can u tell me what mods are incompatiable with the mod

**Comment by MrBreakNFix** [comment]
No, as there are a seemingly infinite amount of mods and its hard to say exactly what of those are incompatible with this one.

**Comment by JustLikeNone** [comment]
k
