### ISSUE TITLE
shift + rmb not working

### ISSUE THREAD

**Issue by OhNoItzBuster** [Coderx-Gamer/ui-utils#12]
so i saw the duper trooper's vid, he says if you do shift + rmb a menu will appear, and it does in his vid, but not in my mc

**Comment by GDMgmer3992** [comment]
You need this plugin
https://www.spigotmc.org/resources/shulkerbox-backpacks.61073/

**Comment by OhNoItzBuster** [comment]
ohhh ok

**Comment by SzczurekYT** [comment]
> ohhh ok

If you understnad now, and you don't have any reason to keep it open, then close it.
