### ISSUE TITLE
Please show the mod menu on open books

### ISSUE THREAD

**Issue by fsdsfsffddfegg** [Coderx-Gamer/ui-utils#126]
I don't see any reason why this shouldn't be implemented.

**Comment by MrBreakNFix** [comment]
could make a separate gui for books possibly, but this would not really be useful for dupe hunting

**Comment by MrBreakNFix** [comment]
Ill look into it in a bit then

**Comment by Coderx-Gamer** [comment]
You might want to look into cmd utils (https://github.com/Coderx-Gamer/cmd-utils), it will probably work better for stuff like this, if it doesn't work well then I might add some features to either mod.

**Comment by MrBreakNFix** [comment]
Use CMD utils for this
