### ISSUE TITLE
LOCK THIS ISUEE I FOUND A SULUTION!!!

### ISSUE THREAD

**Issue by TofferLeel** [Coderx-Gamer/ui-utils#128]
![image_2024-03-06_191835175](https://github.com/Coderx-Gamer/ui-utils/assets/139256851/8a4dfedd-3c28-46f7-97ab-194679a1401d)

**Comment by MrBreakNFix** [comment]
you can press the close issue btw, it exists, also for other people reading this, please read the popups and try to satisfy them before creating an issue.

**Comment by TofferLeel** [comment]
> you can press the close issue btw, it exists, also for other people reading this, please read the popups and try to satisfy them before creating an issue.

I thought it meant like actually the fabric launcher so yeah
