### ISSUE TITLE
Random Error??

### ISSUE THREAD

**Issue by TrippySkills** [Coderx-Gamer/ui-utils#13]
![image](https://user-images.githubusercontent.com/101980847/193335819-8f37ddee-9cbc-42b0-ac5e-28b45bc63e06.png)

**Comment by Anonymous17532** [comment]
You need to download fabric

**Comment by anhtlauncher** [comment]
u need fabric api lol trust me

**Comment by Anonymous17532** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-api

Put this in your mods folder and it will work
