### ISSUE TITLE
Fabric loader says "Incompatible Mods Found!" and says that "Mod 'UI Utils' (uiutils) 1.4.4 requires any version of fabric, which is missing! But I have fabric, do you know what I should do?

### ISSUE THREAD

**Issue by TapeerT** [Coderx-Gamer/ui-utils#132]
![image](https://github.com/Coderx-Gamer/ui-utils/assets/167836045/a1d67e3c-ab7f-4912-ade3-e913ea77ebf3)

**Comment by MrBreakNFix** [comment]
# Install fabric API
![image](https://github.com/Coderx-Gamer/ui-utils/assets/73456238/7ac1c519-c207-497d-9c54-bf3a504930bb)
Please learn how to do correctly in the future as well. Its like an email, you do not put the whole thing in the subject/
