### ISSUE TITLE
1.20.6?

### ISSUE THREAD

**Issue by ModxVoldHunter** [Coderx-Gamer/ui-utils#133]
its a simple release, all you have to do is change a few files like maybe 4 files and then release

**Comment by MrBreakNFix** [comment]
sure, ill release it in a few hours

**Comment by 2n640** [comment]
![Screenshot 2023-07-20 125815](https://github.com/Coderx-Gamer/ui-utils/assets/106294385/3fef8060-89b2-4489-8c1d-e5d9a8530d18)

**Comment by ModxVoldHunter** [comment]
> ![Screenshot 2023-07-20 125815](https://private-user-images.githubusercontent.com/106294385/333027912-3fef8060-89b2-4489-8c1d-e5d9a8530d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MDQxNjIsIm5iZiI6MTcxNjUwMzg2MiwicGF0aCI6Ii8xMDYyOTQzODUvMzMzMDI3OTEyLTNmZWY4MDYwLTg5YjItNDQ4OS04YzFkLWU1ZDlhODUzMGQxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QyMjM3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2Q1Y2UwM2UzNmFmMjNmOTQyNzEyMTdlMmY5YTQyMTgzMjZiYmRiMjgxZWEyMzQyMzFiMzA5YTJjM2FjNWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2wY5rjVFyv_i7v0pFscS26ExxGqAeySHiRbpEUDBBZw)

nooo not the pizza!

**Comment by MrBreakNFix** [comment]
https://modrinth.com/mod/uiutils

<3
