### ISSUE TITLE
Delay packet for duping

### ISSUE THREAD

**Issue by IAMSOEPIC2303** [Coderx-Gamer/ui-utils#136]
People delay their packets and dupe using shulker boxes and player vaults

**Comment by MrBreakNFix** [comment]
please add more information, ex the problem or logs, or instructions on how to reproduce

**Comment by IAMSOEPIC2303** [comment]
I am going to post the link to a youtube channel for the guy who posts all of these dupes using this mod. he has multiple videos https://www.youtube.com/@Sapire

**Comment by IAMSOEPIC2303** [comment]
i personally havent have people used it but its honeslty annoying as shit that ppl r abusing this and i dont want it abused when  i enable vault on my server https://www.9minecraft.net/ui-utils-mod/

**Comment by MrBreakNFix** [comment]
Sorry, but I cannot condone 9minecraft, as they infringe on our license, and we have requested them to take it down. They have not responded. Plus that method has been patched

**Comment by MrBreakNFix** [comment]
Also please keep issues for actual issues of the mod

**Comment by IAMSOEPIC2303** [comment]
ok ty
