### ISSUE TITLE
[Feature Request] Scale UI

### ISSUE THREAD

**Issue by ninjaguardian** [Coderx-Gamer/ui-utils#139]
An options to move/scale the buttons in the inv and multiplayer screen

**Comment by ninjaguardian** [comment]
Also the text in the inv too

**Comment by ninjaguardian** [comment]
It overlaps with everything

**Comment by MrBreakNFix** [comment]
just change gui scale

**Comment by ninjaguardian** [comment]
But that changes all the UI. But you do have a point.

**Comment by MrBreakNFix** [comment]
possibly will do if new UI is added
