### ISSUE TITLE
Crash when using Fabricate Packets (1.20.4)

### ISSUE THREAD

**Issue by SxmmerTime** [Coderx-Gamer/ui-utils#141]
When I click the button I get an error and it crashes
![image](https://github.com/user-attachments/assets/dabb8e72-682b-4309-bdde-22a246b8823a)

**Comment by MrBreakNFix** [comment]
Please provide the latest.log

**Comment by N00B4LXFE** [comment]
Same for me, happened on 1.20.1 

[latest.log](https://github.com/user-attachments/files/16534969/latest.log)
(first sign of crash starts at line 4237)

**Comment by MrBreakNFix** [comment]
Its probably one of the other mods, does it work on its own?

**Comment by N00B4LXFE** [comment]
Sorry for the wait, the regular mod does work on its own

After testing it with all of my mods it seems that my versions of Wurst and Essential cause a crash (I do not update enough)

![image](https://github.com/user-attachments/assets/e6c441b0-4c7e-4591-8b72-28f98eb63be5)

![image](https://github.com/user-attachments/assets/ededad04-b6f8-4f66-ad16-4685bd129cfe)

**Comment by MrBreakNFix** [comment]
Lol, Ill add them to the breaks list
