### ISSUE TITLE
UI Utils on modrinth

### ISSUE THREAD

**Issue by Echrift** [Coderx-Gamer/ui-utils#145]
Ui utils got banned on modrinth. Could you please add ui utils into the github page?

**Comment by MrBreakNFix** [comment]
still waiting for modrinth to respond on this, if its not back up or no explanation within the next 2 or 3 days, sure.
In the meantime, theres a temporary channel in the discord

**Comment by SwishierGamer** [comment]
yoo

**Comment by Echrift** [comment]
holy swishier what are you doing in here
