### ISSUE TITLE
Latest version crashes the game upon opening Inventory

### ISSUE THREAD

**Issue by toomanybarrels** [Coderx-Gamer/ui-utils#21]
I'd put a copy of the crash report, but the crash report gives WAY too many details about my device, so I'll have to summarize:

I'm playing on 1.19.3, opening my inventory crashes my game on both servers and singleplayer worlds, the only other mods I have installed are the Fabric API and ModMenu, and the crash report says there's something wrong with a thing called "void net.minecraft.class_4185"

What should I do? Should I wait for an update, try removing this from the mod, or should I just play on 1.19.2 or something?

**Comment by not2wicked** [comment]
I changed my version and all my mods to 1.19.2 and it worked. 

TLDR: This mod is incompatible with minecraft 1.19.3

**Comment by Coderx-Gamer** [comment]
I updated to 1.19.3.
