### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by theprisoner55** [Coderx-Gamer/ui-utils#23]
![www](https://user-images.githubusercontent.com/110493337/210312270-602afe6e-70f4-4061-a799-9abbe501aac3.PNG)

**Comment by Vxnished** [comment]
yeah, i've the exact same problem

**Comment by CaptainRexPL** [comment]
This mod requires fabric api (0.60.0 version to be exact) so to fix this error you just have to install the correct version of Fabric API.

**Comment by Vxnished** [comment]
ty, maybe someone should write this in read me or something? cuz i couldn't find anything about it
