### ISSUE TITLE
cant use it on mac

### ISSUE THREAD

**Issue by aminscova** [Coderx-Gamer/ui-utils#3]
pls fix i cant use it on mac it doesnt show anything

**Comment by Coderx-Gamer** [comment]
the fabricate packet gui? or just the whole mod? if its the fabricate packet thing it might take a while to fix since I don't use mac.

**Comment by awsomenes** [comment]
yeah the fabricate packet gui, also i can only seem to use the disconnect and send packet option once. Even after closing/reopening the game, the issue still persists

**Comment by old-pot** [comment]
my minecraft client simply just shows a black screen

**Comment by Devc2** [comment]
i think its for pc users ;-;

**Comment by Devc2** [comment]
> i think its for pc users ;-;

i could be wrong

**Comment by aminscova** [comment]
@Coderx-Gamer yep the whole mod, it shows black screen when i open minecraft and i have to force quit it.

**Comment by Checkmate128** [comment]
My game window never focuses which causes the game to be completely unplayable. My game is also not able to be closed and requires a full computer restart to close.

**Comment by Anonymous17532** [comment]
ez download windows vm

**Comment by Anonymous17532** [comment]
I find this works for mac users

https://github.com/FlorianMichael/UI-Utils-Reborn
