### ISSUE TITLE
MInecraft won't load with mod installed

### ISSUE THREAD

**Issue by FreezingDaisy98** [Coderx-Gamer/ui-utils#32]
When I loaded just the mod, fabric said that it requires any version of fabric which doesn't make sense. To try and fix it i added the latest version of fabric api for 1.19.2. With fabric api installed, when i open minecraft the screen is all black and wont load.

**Comment by MrBreakNFix** [comment]
allocate more ram

**Comment by Badbird5907** [comment]
> allocate more ram

![image](https://github.com/Coderx-Gamer/ui-utils/assets/50347938/b2fe2d2e-7d0a-4d3d-96aa-56c0de15a464)
doesn't work, I've allocated 32gb

**Comment by MrBreakNFix** [comment]
lolxd
