### ISSUE TITLE
[question] sugar

### ISSUE THREAD

**Issue by krispyking24** [Coderx-Gamer/ui-utils#35]
why the rename of sugar to cocaine along with adding a sniff sound 
here's the sniff sound commit change
https://github.com/Coderx-Gamer/ui-utils/commit/f188c354f2c3432b91988b8f221f4dc0877a70b7
and here's one of the commits I can find where sugar was renamed to cocaine (its line 2153)
https://github.com/Coderx-Gamer/ui-utils/commit/44851b4a09c32987cf74b4a524a86506092edfae#diff-885d8321aa85697713a8694ba062dcde582b5530052e28b28780e8f3815879cfR2153

**Comment by MrBreakNFix** [comment]
its an intended feature, try right clicking the item ingame.

**Comment by krispyking24** [comment]
ok then what do i need to delete to remove the whole feature

**Comment by MrBreakNFix** [comment]
You dont delete anything, its just a feature.

**Comment by krispyking24** [comment]
so? forks are there for a reason to make changes a different person wants but the original creator doesn't either want or puts in the original

**Comment by krispyking24** [comment]
actually tbh i really don't care what u say about this as one way or another i'm as least removing the renaming of it likely by the en_us.json file in ui-utils/blob/main/src/main/resources/assets/minecraft/lang/en_us.json

**Comment by MrBreakNFix** [comment]
![Hey look, it was the owners idea, not mine!](https://i.imgur.com/xLOMYnh.png)
![Fork yourself and stop coping about it like a 12 year old, its just a minecraft mod](https://media.tenor.com/4U0-YrYUYzsAAAAC/splatoon-peanut.gif)

**Comment by Coderx-Gamer** [comment]
bro its a feature

**Comment by Coderx-Gamer** [comment]
why wouldnt u want a chest of sugar to have all the sugar named cocaine

**Comment by MrBreakNFix** [comment]
ikr we should add this feature back @Coderx-Gamer
