### ISSUE TITLE
i "cant" luanch minecraft

### ISSUE THREAD

**Issue by batman19733** [Coderx-Gamer/ui-utils#40]
when i lunach minecraft its just a black window and i cant click anything
btw i am on macbook so how can i fix it? do i need more mod? i have ui utils fabric and fabric api

**Comment by MrBreakNFix** [comment]
this mod is only guarenteed to work on windows with full functionality, could you maybe send a crash report?

**Comment by PowerRubik** [comment]
same issue

**Comment by MrBreakNFix** [comment]
if you want us to fix it, how about give some more <h1> context
