### ISSUE TITLE
Opening The game with the mod installed error

### ISSUE THREAD

**Issue by achesUwU** [Coderx-Gamer/ui-utils#41]
whenever I put the mod in the folder and I open the game, it is just black screen.Also I am on 1.19.3 if that helps

**Comment by MrBreakNFix** [comment]
send logs?
also try allocating more ram to mc, make sure you are using fabric api and correct version of it and ui utils.

**Comment by achesUwU** [comment]
works now I did not have the right fabric api

**Comment by euhjs** [comment]
> works now I did not have the right fabric api

what is the fabric version?
