### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Forex45** [Coderx-Gamer/ui-utils#42]
Hello, I would like to ask how to install this mod in minecraft and what I need to do it

**Comment by MrBreakNFix** [comment]
bruh
the following responce was genereated by chatgpt:


(just ask chatgpt next time xd)
===========
To download and install the UI-Utils mod with Fabric API, please follow these steps:

Download and install the Fabric Loader: Go to the Fabric website (https://fabricmc.net/use/), download the latest version of the Fabric Loader that corresponds to your Minecraft version, and run the installer.

Download the Fabric API: Go to the Fabric API CurseForge page (https://www.curseforge.com/minecraft/mc-mods/fabric-api), select the version of the Fabric API that corresponds to your Minecraft version, and click the "Download" button. Save the file to your computer.

Download the UI-Utils mod: Go to the UI-Utils GitHub page (https://github.com/Coderx-Gamer/ui-utils/releases), select the latest release, and click the "Assets" drop-down menu. Download the file that ends with ".jar" to your computer.

Move the Fabric API and UI-Utils mod files to the Minecraft mods folder: Open your Minecraft game directory, go to the "mods" folder, and move the Fabric API and UI-Utils mod files from your downloads folder to the "mods" folder.

Launch Minecraft with the Fabric profile: Open the Minecraft launcher, click the "Installations" tab, and click the "New" button to create a new installation. In the "Version" drop-down menu, select the Fabric version that corresponds to your Minecraft version, and give your installation a name. Click the "Create" button, then click the "Play" button to launch Minecraft with the Fabric profile.

Verify that the mod is installed: Once you are in the game, open any inventory or container, and you should see the UI-Utils mod buttons appear.

That's it! You have successfully downloaded and installed the UI-Utils mod with Fabric API.
