### ISSUE TITLE
Game crash when i open chest crafting table ect

### ISSUE THREAD

**Issue by euhjs** [Coderx-Gamer/ui-utils#43]

**Comment by MrBreakNFix** [comment]
![image](https://user-images.githubusercontent.com/73456238/223039458-ed67cd2c-8bd2-4282-9bbe-b9e0ca38d929.png)
maybe some more <h1>* context *

**Comment by User9688** [comment]
I download ui utils 1.19.4 mod and put into mods folder when i start game my game crash and fabrics error pls 😭😭😭😭 fix this

**Comment by MrBreakNFix** [comment]
bro send logs xd
