### ISSUE TITLE
i have macbook to to install it?

### ISSUE THREAD

**Issue by batman19733** [Coderx-Gamer/ui-utils#44]

**Comment by Pxddyk45** [comment]
As said in the readme, it's incompatible with mac

**Comment by batman19733** [comment]
:(

**Comment by MrBreakNFix** [comment]
some features are broken on mac but it still should work somewhat

**Comment by Pxddyk45** [comment]
> some features are broken on mac but it still should work somewhat

for me, it just shows a black screen on startup
