### ISSUE TITLE
Stuck on a black screen

### ISSUE THREAD

**Issue by GoldFG** [Coderx-Gamer/ui-utils#45]
Whenever I try loading Minecraft with this mod i'm stuck on a black screen.

**Comment by GoldFG** [comment]
<img width="865" alt="Screenshot 2023-03-16 at 11 47 35" src="https://user-images.githubusercontent.com/128047266/225607638-3a9cb144-cee4-44e5-836f-0a2965b32b98.png">

**Comment by Coderx-Gamer** [comment]
![image](https://user-images.githubusercontent.com/85349822/225780922-79527fc9-1af9-497f-a250-d6abdce15f10.png)
