### ISSUE TITLE
When ever I open a gui, (villager, chest, invertory etc.) it instantly crashes

### ISSUE THREAD

**Issue by FractalingCoder** [Coderx-Gamer/ui-utils#47]
When ever I right click a villager, or open my inventory, is crashes, giving me the error code:

.The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'

Im also using a windows 10 pc if thats any help

**Comment by mid3vilchase** [comment]
same

**Comment by MrBreakNFix** [comment]
please provide more information (crashlog, screenshot)

**Comment by juishyy** [comment]
I haave the same problem, here is the whole error code: `---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-06-05 08:27:12
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at net.minecraft.class_465.handler$zkd004$uiutils$init(class_465.java:739)
	at net.minecraft.class_465.method_25426(class_465.java:92)
	at net.minecraft.class_490.method_25426(class_490.java:58)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_310.method_1508(class_310.java:1993)
	at net.minecraft.class_310.method_1574(class_310.java:1863)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_465.handler$zkd004$uiutils$init(class_465.java:739)
	at net.minecraft.class_465.method_25426(class_465.java:92)
	at net.minecraft.class_490.method_25426(class_490.java:58)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_310.method_1508(class_310.java:1993)

-- Affected level --
Details:
	All players: 27 total; [class_746['Juishe'/4980, l='ClientLevel', x=-43.51, y=75.00, z=148.42], class_745['§lFisuPvP'/265, l='ClientLevel', x=-30.50, y=75.00, z=155.50], class_745['NPC_dtm'/268, l='ClientLevel', x=-31.46, y=75.50, z=139.50], class_745['CIT-b0a0415c9c87'/262, l='ClientLevel', x=-32.47, y=74.00, z=186.56], class_745['CIT-5c45f2d999eb'/253, l='ClientLevel', x=-38.50, y=74.00, z=186.50], class_745['CIT-d5f7186acffb'/182, l='ClientLevel', x=-38.51, y=74.00, z=187.54], class_745['npc_prison'/149, l='ClientLevel', x=-55.50, y=75.50, z=139.53], class_745['§eGeqa'/215, l='ClientLevel', x=-29.48, y=74.00, z=194.32], class_745['survival'/86, l='ClientLevel', x=-49.57, y=75.50, z=135.36], class_745['tapahtuma'/206, l='ClientLevel', x=-29.56, y=75.50, z=142.51], class_745['CIT-fd041f961a54'/256, l='ClientLevel', x=-38.50, y=74.00, z=185.50], class_745['CIT-60379b42f41d'/271, l='ClientLevel', x=-27.57, y=74.00, z=191.52], class_745['Vesitaisto_NPC'/238, l='ClientLevel', x=-34.50, y=75.50, z=136.50], class_745['CIT-745edf671e4f'/101, l='ClientLevel', x=-27.49, y=74.00, z=193.48], class_745['CIT-3e6e9cdd5ac3'/158, l='ClientLevel', x=-36.52, y=74.00, z=183.47], class_745['CIT-772197f30406'/98, l='ClientLevel', x=-27.51, y=74.00, z=190.51], class_745['§cJohvu'/230, l='ClientLevel', x=-54.59, y=58.06, z=117.30], class_745['CIT-30c432bbaaeb'/161, l='ClientLevel', x=-34.54, y=74.00, z=183.48], class_745['§eKeministi'/224, l='ClientLevel', x=-30.52, y=74.00, z=194.50], class_745['§eTiuskiii'/221, l='ClientLevel', x=-29.51, y=74.00, z=187.48], class_745['Lohja'/233, l='ClientLevel', x=-54.50, y=58.06, z=112.54], class_745['Luckywars_NPC'/241, l='ClientLevel', x=-37.48, y=75.50, z=135.52], class_745['§a§lKauppias'/244, l='ClientLevel', x=-36.50, y=75.00, z=161.50], class_745['CIT-cd346836e979'/250, l='ClientLevel', x=-32.50, y=74.00, z=185.50], class_745['Creative_NPC'/227, l='ClientLevel', x=-52.50, y=75.50, z=136.50], class_745['CIT-b0b77bc46cc5'/89, l='ClientLevel', x=-27.45, y=74.00, z=192.49], class_745['CIT-7f4e2a8dc8e8'/259, l='ClientLevel', x=-35.55, y=74.00, z=182.41]]
	Chunk stats: 441, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (-44,75,148), Section: (at 4,11,4 in -3,4,9; chunk contains blocks -48,-64,144 to -33,319,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 26081 game time, 1000 day time
	Server brand: Purpur (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, Fabric Mods, server

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 997936104 bytes (951 MiB) / 1845493760 bytes (1760 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700 Eight-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.9001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24526.60
	Virtual memory used (MB): 17701.08
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 109.69
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.76.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.22+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.39+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.2+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.13+b5470ac785
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.21+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.25+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.32+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.2+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+68296ad585
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.14.21
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		uiutils: UI Utils 1.0.0
	Launched Version: fabric-loader-0.14.21-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.0 Core Profile Context 22.20.27.09.230330, ATI Technologies Inc.
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: English (United Kingdom)
	CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor `

**Comment by MrBreakNFix** [comment]
very weird, is this still happening?

**Comment by LonelyKat** [comment]
It is still happening to me yes

**Comment by MrBreakNFix** [comment]
fixed in new version to my experience
