### ISSUE TITLE
Is it possible to get 1.19 support?

### ISSUE THREAD

**Issue by Asgerspange** [Coderx-Gamer/ui-utils#5]

**Comment by Anonymous17532** [comment]
just port it its not hard

**Comment by JABirchall** [comment]
Just use ViaVersion https://www.curseforge.com/minecraft/mc-mods/viafabric
Supports 0.19.2 connecting to Minecraft servers all the way to 0.8.9

**Comment by Anonymous17532** [comment]
^^^
you can also use multiconnect
