### ISSUE TITLE
how do i run this?

### ISSUE THREAD

**Issue by Endlessvoid303** [Coderx-Gamer/ui-utils#53]

**Comment by Endlessvoid303** [comment]
it gives errors when i start gradlw.bat

**Comment by MrBreakNFix** [comment]
you right click the jar file, then click delte

**Comment by Eragon1250** [comment]
Create a folder i your minecraft folder called "mods" put The .jar file in, put the version of fabric-api thats matchs the "ui utils" version also in the folder, look in the minecraft launcher under the versions untill you find fabric, start it
