### ISSUE TITLE
Hey Devs of this mod can you please get a 1.19 version so I can use it on a server i play on?

### ISSUE THREAD

**Issue by Topdragon343** [Coderx-Gamer/ui-utils#6]

**Comment by JABirchall** [comment]
Just use ViaVersion https://www.curseforge.com/minecraft/mc-mods/viafabric
Supports 0.19.2 connecting to Minecraft servers all the way to 0.8.9

**Comment by Anonymous17532** [comment]
You could use viaversion or multiconnect

(also duplicate issue so I'm closing)
