### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Manlosisimo** [Coderx-Gamer/ui-utils#60]
@Coderx-Gamer
We have the code/mod/hack, but how is it installed to be able to use it?

**Comment by Eragon1250** [comment]
Create a folder i your minecraft folder called "mods" put The .jar file in, put the version of fabric-api thats matchs the "ui utils" version also in the folder, look in the minecraft launcher under the versions untill you find fabric, start it

**Comment by Daenerys4KTREY** [comment]
> Create a folder i your minecraft folder called "mods" put The .jar file in, put the version of fabric-api thats matchs the "ui utils" version also in the folder, look in the minecraft launcher under the versions untill you find fabric, start it

But what is the jar file like the name i cant actually find it the folder

**Comment by MrBreakNFix** [comment]
yep thats right

**Comment by MrBreakNFix** [comment]
https://github.com/Coderx-Gamer/ui-utils/releases/tag/1.2.2

thats the jars
