### ISSUE TITLE
[ Suggestion ] Freeze Gui.

### ISSUE THREAD

**Issue by Godwhitelight** [Coderx-Gamer/ui-utils#61]
Block Gui changes, such as closing or opening a new Gui. Yet. send the packets!
or you can make a GUI history instead and be able to change to older Guis

**Comment by MrBreakNFix** [comment]
please explain in more detail and i might add it

**Comment by Godwhitelight** [comment]
Some sort of history to the jew or a way to block the server from changing the gui.
So if u click an anvil and the server opens some other gui instead u could block them from opening a new one after it. so it will only open the first gui.

**Comment by MrBreakNFix** [comment]
most of the time, they cancle the first gui server side, but i might have an idea, just store all the screens in an array that can be called later

**Comment by Godwhitelight** [comment]
yh that would work

**Comment by MrBreakNFix** [comment]
its possible, just not fun to do because all the screens pushed server side breaks it.

**Comment by Godwhitelight** [comment]
its very possible. it would be hard but cool af
