### ISSUE TITLE
Can this dupe items?

### ISSUE THREAD

**Issue by SirReddev** [Coderx-Gamer/ui-utils#62]

**Comment by SirReddev** [comment]
I am wondering if this would work with some sort of npc show or villager

**Comment by MrBreakNFix** [comment]
yes it can if you can figure out how to do it

**Comment by GamebP** [comment]
who has a tutorial how to do it. im trying for he past 4hours, nothing works... only ghost items.

**Comment by GamebP** [comment]
https://www.youtube.com/results?search_query=ui-utils+1.19.2 ?
