### ISSUE TITLE
"Failed to login: Invalid session (Try restarting your game)"

### ISSUE THREAD

**Issue by Eragon1250** [Coderx-Gamer/ui-utils#65]
i get the "Failed to login: Invalid session (Try restarting your game)" Error when trying to log into any Server(Singleplayer works).

**Comment by Eragon1250** [comment]
Restarting my Commputer fixed the Problem, everything works fine now

**Comment by MrBreakNFix** [comment]
bruh

u just need to relog

**Comment by Eragon1250** [comment]
restarting game didnt worked

**Comment by Cabbasca** [comment]
this is not an issue with the mod go elsewhere

**Comment by MrBreakNFix** [comment]
exactly, only a month late!

**Comment by Eragon1250** [comment]
> this is not an issue with the mod go elsewhere

the issue is fixed, after first using the mod i didnt got onto servers anymore, restarting the game didnt fixed it, restarting my commputer did, everything is fine now.

if someone else has the same issue he can see my post here and do the same i did and everything will be finde for him to.
