### ISSUE TITLE
Not working, tried every step

### ISSUE THREAD

**Issue by TheROBLOXGoat** [Coderx-Gamer/ui-utils#76]
When I went to try to copy items, nothing was working even when I did it the right way, is it maybe that this has been fixed? Using 1.19.3 CurseForge Fabric. The only plugins on the server im playing on is the Homespawn along with the Wavepoint plugins, no anti-cheats.
![Notworking](https://github.com/Coderx-Gamer/ui-utils/assets/39636923/0e154187-386c-4abd-93dd-6c7f444886bd)

**Comment by MrBreakNFix** [comment]
you mean dupe items? you kinda need to find your own, it does not just dupe on ever server
