### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by oZowlz** [Coderx-Gamer/ui-utils#79]
Hi. I download the "ui-utils-main.zip".
After that i unpack it and drag bothe the zip and the extracted files to my mods folder.
I launch Minectaft with latest fabric and api.
But when i load into a server and try open inventory/storages, the "ui tools" are not there.

I personally have no idea what to do now. 
I also do not find any jar file for ui tools in the files all i see is the graddle.bat and a graddle.jar file. 

I have tried to google/yt this problem, but I do not find any solution what so ever.

If you have any ideas on how to install this or even a tutorial iw ould gladly appreciate this.

Have a good day fellow coders!

**Comment by oZowlz** [comment]
I have figured it out. I found the files

**Comment by Daenerys4KTREY** [comment]
> I have figured it out. I found the files

Hey dude can u tell me what was the name of the file ? 
I cant actually find it

**Comment by MrBreakNFix** [comment]
You need fabric API and fabric loader too, the jar file is here. 
Stop downloading the zip unless you build it yourself:

https://github.com/Coderx-Gamer/ui-utils/releases/tag/1.2.2
