### ISSUE TITLE
How do you download the mod

### ISSUE THREAD

**Issue by Coltonfr5** [Coderx-Gamer/ui-utils#80]
I have tried downloading the mod multiple times, I opened the .bat files and looked through all the code, I am still confused however and can't figure out a way to get this to work. 
![image](https://github.com/Coderx-Gamer/ui-utils/assets/102493493/1d6a9c2b-eb55-4e04-9815-c75f2f8450c3)
this is what I have got so far on what I might need to do, there is a .gaddle file so I should probably move that out but then I go to this problem of finding the .jar file.
![image](https://github.com/Coderx-Gamer/ui-utils/assets/102493493/a9b9ca7e-6bd7-4011-91d0-1fcc3ff6a8af)
only one I found was this .jar file so far, I looked everywhere.
![image](https://github.com/Coderx-Gamer/ui-utils/assets/102493493/29c9ba1c-749f-4cbd-b21c-1d12f2eeefaf)
as I am confused I am wondering how to work this and how I could use the mod.
I am really fascinated on how this works but I don't know how to install the mod.
![image](https://github.com/Coderx-Gamer/ui-utils/assets/102493493/b91a5312-ae1e-4c49-b14a-f2f71a6e1993)
I put it through here but I don't see how it works as when I launch anything there are no ui options.
![image](https://github.com/Coderx-Gamer/ui-utils/assets/102493493/d1d84e11-4926-4daf-84c1-c18534517b9a)
I looked on youtube and read all the "Issues" to find out a way to install this, maybe a detailed guide? I am still confused on how to do all of this.
Hope that you can fix this and stuff thanks :]
(also maybe a guide inside the files would not be a bad idea, maybe a .txt file would work or another .mb file).

**Comment by MrBreakNFix** [comment]
you need fabric api, and the jar found in the releases

**Comment by Coltonfr5** [comment]
> you need fabric api, and the jar found in the releases

I have the fabric api, and I got the .bat downloaded, do I keep the .gaddle in my .minecraft folder and just put in the .jar file into my mods?

**Comment by MrBreakNFix** [comment]
UI utils jar: https://github.com/Coderx-Gamer/ui-utils/releases/download/1.2.2/ui-utils_1.19.4_1.2.2.jar

fabric API: https://www.curseforge.com/api/v1/mods/306612/files/4559040/download

drop those both in your mod folder, with fabric mod loader, in 1.19.4 (not mac) and it should be good!

Fabric mod loader: https://fabricmc.net/use/installer/

**Comment by MrBreakNFix** [comment]
you don't need to worry about any of the gradle files, that is if you want to make the jar yourself which I am assuming you do not want to do.

**Comment by Coltonfr5** [comment]
thanks, the explanation helps a bit, maybe you should put this in your files for the download thing.

**Comment by MrBreakNFix** [comment]
for most people I believe it is self explanatory, if it is needed, I will add it to the readme.

**Comment by Coltonfr5** [comment]
It was not that explanitory as I did not look in the releases for the begininng of it and just looked into the regular thing that was hooked with the homepage of the github, but maybe it was explanitory I just could not read.

**Comment by Coltonfr5** [comment]
> for most people I believe it is self explanatory, if it is needed, I will add it to the readme.

would this work for versions like 1.8.9 or 1.12.4 etc? if it does not work I wont push you or tell you to make one just a question, I might try it rn but it's just a quick question.
