### ISSUE TITLE
[Forge] Doesn't show in the mods menu

### ISSUE THREAD

**Issue by fortfort-rov** [Coderx-Gamer/ui-utils#81]
In the mods menu, it shows Minecraft and Forge, but no ui-utils. I've checked several times to be sure that it's in there, but it just won't work. This could likely be a Forge issue, as the only Forge version that has been working for me with mods is 1.12.2. I've even tried reinstalling all versions of forge, and it just won't work.

**Comment by a7md8762** [comment]
this mod is for fabric 1.19+ not forge dumbass

**Comment by fortfort-rov** [comment]
Ah, okay.
