### ISSUE TITLE
Please make support for 1.19.1-1.19

### ISSUE THREAD

**Issue by NotRenzyXlezy** [Coderx-Gamer/ui-utils#88]
Make support for 1.19 and 1.19.1!!1111!1!!😡😡😡

**Comment by MafioLive** [comment]
see how the tab says "Issues", This is not an issue. if you want support for 1.19-1.19.1, write the code for it yourself and make a pull request.

**Comment by NotRenzyXlezy** [comment]
> see how the tab says "Issues", This is not an issue. if you want support for 1.19-1.19.1, write the code for it yourself and make a pull request. also stop making requests for this.

bro i can't even create it its just sending me a error

**Comment by MrBreakNFix** [comment]
See how it says issues, this is not an issue, see how many other people asked this, this is a duplicate, also viaversion exists
