### ISSUE TITLE
Create a Discord server

### ISSUE THREAD

**Issue by itzyongan** [Coderx-Gamer/ui-utils#91]
Create a Discord server for support / community so we can discuss related to the mod.

**Comment by MrBreakNFix** [comment]
not a bad idea

**Comment by itzyongan** [comment]
> Personally, I think it'd be better if he creates a community server on guilded.gg for example, as to not violate the Discord's TOS and not on the edges of getting termed anytime.

Yeah, but the Minecraft players base is mostly on Discord, including me. Meteor Client’s Discord server hasn’t even been terminated yet.

**Comment by MrBreakNFix** [comment]
Its here!

https://discord.com/invite/DfTadNqQEA

Still work in progress though!
