### ISSUE TITLE
i have mac

### ISSUE THREAD

**Issue by batman19733** [Coderx-Gamer/ui-utils#95]
the mod says it wont work on mac and i only have mac can make me another version of the mod for mac? please

**Comment by batman19733** [comment]
why not?

**Comment by batman19733** [comment]
what with ppl with mac?

**Comment by MafioLive** [comment]
Install windows on your Mac using bootcamp if you want to use the mod, otherwise stop.

**Comment by batman19733** [comment]
cant
but cant you or the crator of the mod to make a simmair mod that works on mac?

**Comment by MafioLive** [comment]
Cant

**Comment by MrBreakNFix** [comment]
STOP asking for us to make this work with mac, it has been made clear multiple times that we will NOT make this work!

If we change our minds, I will update the readme, but as of now, all issues having to do with mac are invalid and will be marked with a wontfix.

You have several options, you can boot on a different OS such as Linux, or windows, or you can look at the forks, I believe some are compatible with mac, or you can spam my email until I get annoyed enough to fix it.

**Comment by Paddyk45** [comment]
> STOP asking for us to make this work with mac, it has been made clear multiple times that we will NOT make this work!
> 
> If we change our minds, I will update the readme, but as of now, all issues having to do with mac are invalid and will be marked with a wontfix.
> 
> You have several options, you can boot on a different OS such as Linux, or windows, or you can look at the forks, I believe some are compatible with mac, or you can spam my email until I get annoyed enough to fix it.

What about #68

**Comment by LeonTab1** [comment]
hey. When I want to run the software this pops up: "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'uiutils'!"
Exit code: -1
anyone knows how to fix this?

**Comment by MrBreakNFix** [comment]
not enough info

**Comment by LeonTab1** [comment]
I use Fabric api-0.83.0+1.20.1 and Fabric 1.20.1 The version I´m trying to use is 1.20.1 (1.3.2)

**Comment by LeonTab1** [comment]
![grafik](https://github.com/Coderx-Gamer/ui-utils/assets/118841691/9bc326d0-3e02-4df3-b26c-c7a8cf8104ac)

**Comment by MrBreakNFix** [comment]
Can you provide the crash log, also are you on mac?
