### ISSUE TITLE
When Click on 'Close without Packets' closes with Packets...

### ISSUE THREAD

**Issue by TiredGreenify** [Coderx-Gamer/ui-utils#96]
I played on a server where the duping worked perfectly fine. However recently (1.19.4), I do the same thing but when I click on Close without Packet, it closes with packet. It drops the item on the ground like normal but when I open the Ender-Chest again, the item isn't there which means it isn't duping anymore.

**Comment by MrBreakNFix** [comment]
that's just called they fixed the dupe, nothing is wrong with the mod lol.

ask the server owner to add a dupe plugin if you want, because I think they patched it for a reason.
