### ISSUE TITLE
mod problem

### ISSUE THREAD

**Issue by lemonadass** [Coderx-Gamer/ui-utils#98]
I installed fabric 1.19.4 for this then i installed 1.19.4 version of this mod but it gives me an error and i can't launch it . It says:
Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
Install fabric, any version.
Unmet dependency listing:
Mod 'UI Utils' (uiutils) 1.2.2 requires any version of fabric, which is missing!

**Comment by MrBreakNFix** [comment]
you also need fabric api, fabric and fabric api are 2 different things, put the fabric api jar file in your mods folder also to fix this, as it is not actually an issue with the mod.
